package com.spider.mybatis.mapper;

import com.spider.mybatis.entity.ArticleInfoText;
import com.spider.mybatis.entity.ArticleInfoTextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleInfoTextMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int countByExample(ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByExample(ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer crawlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insert(ArticleInfoText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insertSelective(ArticleInfoText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	List<ArticleInfoText> selectByExampleWithBLOBs(
			ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	List<ArticleInfoText> selectByExample(ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	ArticleInfoText selectByPrimaryKey(Integer crawlId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") ArticleInfoText record,
			@Param("example") ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") ArticleInfoText record,
			@Param("example") ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") ArticleInfoText record,
			@Param("example") ArticleInfoTextExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(ArticleInfoText record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_crawl_text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKeyWithBLOBs(ArticleInfoText record);
}