package com.spider.mybatis.mapper;

import com.spider.mybatis.entity.PtfDayNum;
import com.spider.mybatis.entity.PtfDayNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtfDayNumMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int countByExample(PtfDayNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByExample(PtfDayNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insert(PtfDayNum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insertSelective(PtfDayNum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	List<PtfDayNum> selectByExample(PtfDayNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	PtfDayNum selectByPrimaryKey(Integer numId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") PtfDayNum record,
			@Param("example") PtfDayNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") PtfDayNum record,
			@Param("example") PtfDayNumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(PtfDayNum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_day_num
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKey(PtfDayNum record);
}