package com.spider.mybatis.mapper;

import com.spider.mybatis.entity.WebsiteInfo;
import com.spider.mybatis.entity.WebsiteInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int countByExample(WebsiteInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByExample(WebsiteInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer websiteId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insert(WebsiteInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insertSelective(WebsiteInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	List<WebsiteInfo> selectByExample(WebsiteInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	WebsiteInfo selectByPrimaryKey(Integer websiteId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") WebsiteInfo record,
			@Param("example") WebsiteInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") WebsiteInfo record,
			@Param("example") WebsiteInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(WebsiteInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKey(WebsiteInfo record);
}