package com.spider.mybatis.mapper;

import com.spider.mybatis.entity.WebsiteInfoParser;
import com.spider.mybatis.entity.WebsiteInfoParserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteInfoParserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int countByExample(WebsiteInfoParserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByExample(WebsiteInfoParserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer parserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insert(WebsiteInfoParser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int insertSelective(WebsiteInfoParser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	List<WebsiteInfoParser> selectByExample(WebsiteInfoParserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	WebsiteInfoParser selectByPrimaryKey(Integer parserId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExampleSelective(@Param("record") WebsiteInfoParser record,
			@Param("example") WebsiteInfoParserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByExample(@Param("record") WebsiteInfoParser record,
			@Param("example") WebsiteInfoParserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKeySelective(WebsiteInfoParser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website_parser
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	int updateByPrimaryKey(WebsiteInfoParser record);
}