package com.spider.mybatis.entity;

public class ArticleInfoText {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_text.crawl_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer crawlId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_crawl_text.text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_text.crawl_id
	 * @return  the value of ptf_crawl_text.crawl_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getCrawlId() {
		return crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_text.crawl_id
	 * @param crawlId  the value for ptf_crawl_text.crawl_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setCrawlId(Integer crawlId) {
		this.crawlId = crawlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_crawl_text.text
	 * @return  the value of ptf_crawl_text.text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_crawl_text.text
	 * @param text  the value for ptf_crawl_text.text
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setText(String text) {
		this.text = text;
	}
}