package com.spider.mybatis.entity;

public class UserWebsite {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_user_website.id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_user_website.user_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_user_website.website_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer websiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_user_website.deleted
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer deleted;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_user_website.id
	 * @return  the value of ptf_user_website.id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_user_website.id
	 * @param id  the value for ptf_user_website.id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_user_website.user_id
	 * @return  the value of ptf_user_website.user_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_user_website.user_id
	 * @param userId  the value for ptf_user_website.user_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_user_website.website_id
	 * @return  the value of ptf_user_website.website_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_user_website.website_id
	 * @param websiteId  the value for ptf_user_website.website_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_user_website.deleted
	 * @return  the value of ptf_user_website.deleted
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_user_website.deleted
	 * @param deleted  the value for ptf_user_website.deleted
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}
}