package com.spider.mybatis.entity;

import java.util.Date;

public class WebsiteInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.website_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer websiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.istask
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer istask;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.rank
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer rank;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.url_home
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private String urlHome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.web_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private String webName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.section_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private String sectionName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.c_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer cId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.c_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private String cName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.c_date
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Date cDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.c_ip
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer cIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_website.isOrder
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	private Integer isorder;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.website_id
	 * @return  the value of ptf_website.website_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.website_id
	 * @param websiteId  the value for ptf_website.website_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.istask
	 * @return  the value of ptf_website.istask
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getIstask() {
		return istask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.istask
	 * @param istask  the value for ptf_website.istask
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setIstask(Integer istask) {
		this.istask = istask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.rank
	 * @return  the value of ptf_website.rank
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getRank() {
		return rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.rank
	 * @param rank  the value for ptf_website.rank
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.url_home
	 * @return  the value of ptf_website.url_home
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public String getUrlHome() {
		return urlHome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.url_home
	 * @param urlHome  the value for ptf_website.url_home
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setUrlHome(String urlHome) {
		this.urlHome = urlHome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.web_name
	 * @return  the value of ptf_website.web_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public String getWebName() {
		return webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.web_name
	 * @param webName  the value for ptf_website.web_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setWebName(String webName) {
		this.webName = webName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.section_name
	 * @return  the value of ptf_website.section_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public String getSectionName() {
		return sectionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.section_name
	 * @param sectionName  the value for ptf_website.section_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.c_id
	 * @return  the value of ptf_website.c_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.c_id
	 * @param cId  the value for ptf_website.c_id
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setcId(Integer cId) {
		this.cId = cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.c_name
	 * @return  the value of ptf_website.c_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public String getcName() {
		return cName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.c_name
	 * @param cName  the value for ptf_website.c_name
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setcName(String cName) {
		this.cName = cName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.c_date
	 * @return  the value of ptf_website.c_date
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Date getcDate() {
		return cDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.c_date
	 * @param cDate  the value for ptf_website.c_date
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setcDate(Date cDate) {
		this.cDate = cDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.c_ip
	 * @return  the value of ptf_website.c_ip
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getcIp() {
		return cIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.c_ip
	 * @param cIp  the value for ptf_website.c_ip
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setcIp(Integer cIp) {
		this.cIp = cIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_website.isOrder
	 * @return  the value of ptf_website.isOrder
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Integer getIsorder() {
		return isorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_website.isOrder
	 * @param isorder  the value for ptf_website.isOrder
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setIsorder(Integer isorder) {
		this.isorder = isorder;
	}
}