package com.spider.mybatis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WebsiteInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public WebsiteInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andWebsiteIdIsNull() {
			addCriterion("website_id is null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdIsNotNull() {
			addCriterion("website_id is not null");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdEqualTo(Integer value) {
			addCriterion("website_id =", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdNotEqualTo(Integer value) {
			addCriterion("website_id <>", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdGreaterThan(Integer value) {
			addCriterion("website_id >", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("website_id >=", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdLessThan(Integer value) {
			addCriterion("website_id <", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdLessThanOrEqualTo(Integer value) {
			addCriterion("website_id <=", value, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdIn(List<Integer> values) {
			addCriterion("website_id in", values, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdNotIn(List<Integer> values) {
			addCriterion("website_id not in", values, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdBetween(Integer value1, Integer value2) {
			addCriterion("website_id between", value1, value2, "websiteId");
			return (Criteria) this;
		}

		public Criteria andWebsiteIdNotBetween(Integer value1, Integer value2) {
			addCriterion("website_id not between", value1, value2, "websiteId");
			return (Criteria) this;
		}

		public Criteria andIstaskIsNull() {
			addCriterion("istask is null");
			return (Criteria) this;
		}

		public Criteria andIstaskIsNotNull() {
			addCriterion("istask is not null");
			return (Criteria) this;
		}

		public Criteria andIstaskEqualTo(Integer value) {
			addCriterion("istask =", value, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskNotEqualTo(Integer value) {
			addCriterion("istask <>", value, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskGreaterThan(Integer value) {
			addCriterion("istask >", value, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskGreaterThanOrEqualTo(Integer value) {
			addCriterion("istask >=", value, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskLessThan(Integer value) {
			addCriterion("istask <", value, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskLessThanOrEqualTo(Integer value) {
			addCriterion("istask <=", value, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskIn(List<Integer> values) {
			addCriterion("istask in", values, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskNotIn(List<Integer> values) {
			addCriterion("istask not in", values, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskBetween(Integer value1, Integer value2) {
			addCriterion("istask between", value1, value2, "istask");
			return (Criteria) this;
		}

		public Criteria andIstaskNotBetween(Integer value1, Integer value2) {
			addCriterion("istask not between", value1, value2, "istask");
			return (Criteria) this;
		}

		public Criteria andRankIsNull() {
			addCriterion("rank is null");
			return (Criteria) this;
		}

		public Criteria andRankIsNotNull() {
			addCriterion("rank is not null");
			return (Criteria) this;
		}

		public Criteria andRankEqualTo(Integer value) {
			addCriterion("rank =", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotEqualTo(Integer value) {
			addCriterion("rank <>", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankGreaterThan(Integer value) {
			addCriterion("rank >", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankGreaterThanOrEqualTo(Integer value) {
			addCriterion("rank >=", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankLessThan(Integer value) {
			addCriterion("rank <", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankLessThanOrEqualTo(Integer value) {
			addCriterion("rank <=", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankIn(List<Integer> values) {
			addCriterion("rank in", values, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotIn(List<Integer> values) {
			addCriterion("rank not in", values, "rank");
			return (Criteria) this;
		}

		public Criteria andRankBetween(Integer value1, Integer value2) {
			addCriterion("rank between", value1, value2, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotBetween(Integer value1, Integer value2) {
			addCriterion("rank not between", value1, value2, "rank");
			return (Criteria) this;
		}

		public Criteria andUrlHomeIsNull() {
			addCriterion("url_home is null");
			return (Criteria) this;
		}

		public Criteria andUrlHomeIsNotNull() {
			addCriterion("url_home is not null");
			return (Criteria) this;
		}

		public Criteria andUrlHomeEqualTo(String value) {
			addCriterion("url_home =", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeNotEqualTo(String value) {
			addCriterion("url_home <>", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeGreaterThan(String value) {
			addCriterion("url_home >", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeGreaterThanOrEqualTo(String value) {
			addCriterion("url_home >=", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeLessThan(String value) {
			addCriterion("url_home <", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeLessThanOrEqualTo(String value) {
			addCriterion("url_home <=", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeLike(String value) {
			addCriterion("url_home like", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeNotLike(String value) {
			addCriterion("url_home not like", value, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeIn(List<String> values) {
			addCriterion("url_home in", values, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeNotIn(List<String> values) {
			addCriterion("url_home not in", values, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeBetween(String value1, String value2) {
			addCriterion("url_home between", value1, value2, "urlHome");
			return (Criteria) this;
		}

		public Criteria andUrlHomeNotBetween(String value1, String value2) {
			addCriterion("url_home not between", value1, value2, "urlHome");
			return (Criteria) this;
		}

		public Criteria andWebNameIsNull() {
			addCriterion("web_name is null");
			return (Criteria) this;
		}

		public Criteria andWebNameIsNotNull() {
			addCriterion("web_name is not null");
			return (Criteria) this;
		}

		public Criteria andWebNameEqualTo(String value) {
			addCriterion("web_name =", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotEqualTo(String value) {
			addCriterion("web_name <>", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameGreaterThan(String value) {
			addCriterion("web_name >", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameGreaterThanOrEqualTo(String value) {
			addCriterion("web_name >=", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameLessThan(String value) {
			addCriterion("web_name <", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameLessThanOrEqualTo(String value) {
			addCriterion("web_name <=", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameLike(String value) {
			addCriterion("web_name like", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotLike(String value) {
			addCriterion("web_name not like", value, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameIn(List<String> values) {
			addCriterion("web_name in", values, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotIn(List<String> values) {
			addCriterion("web_name not in", values, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameBetween(String value1, String value2) {
			addCriterion("web_name between", value1, value2, "webName");
			return (Criteria) this;
		}

		public Criteria andWebNameNotBetween(String value1, String value2) {
			addCriterion("web_name not between", value1, value2, "webName");
			return (Criteria) this;
		}

		public Criteria andSectionNameIsNull() {
			addCriterion("section_name is null");
			return (Criteria) this;
		}

		public Criteria andSectionNameIsNotNull() {
			addCriterion("section_name is not null");
			return (Criteria) this;
		}

		public Criteria andSectionNameEqualTo(String value) {
			addCriterion("section_name =", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotEqualTo(String value) {
			addCriterion("section_name <>", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameGreaterThan(String value) {
			addCriterion("section_name >", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameGreaterThanOrEqualTo(String value) {
			addCriterion("section_name >=", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameLessThan(String value) {
			addCriterion("section_name <", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameLessThanOrEqualTo(String value) {
			addCriterion("section_name <=", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameLike(String value) {
			addCriterion("section_name like", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotLike(String value) {
			addCriterion("section_name not like", value, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameIn(List<String> values) {
			addCriterion("section_name in", values, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotIn(List<String> values) {
			addCriterion("section_name not in", values, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameBetween(String value1, String value2) {
			addCriterion("section_name between", value1, value2, "sectionName");
			return (Criteria) this;
		}

		public Criteria andSectionNameNotBetween(String value1, String value2) {
			addCriterion("section_name not between", value1, value2,
					"sectionName");
			return (Criteria) this;
		}

		public Criteria andCIdIsNull() {
			addCriterion("c_id is null");
			return (Criteria) this;
		}

		public Criteria andCIdIsNotNull() {
			addCriterion("c_id is not null");
			return (Criteria) this;
		}

		public Criteria andCIdEqualTo(Integer value) {
			addCriterion("c_id =", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotEqualTo(Integer value) {
			addCriterion("c_id <>", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThan(Integer value) {
			addCriterion("c_id >", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("c_id >=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThan(Integer value) {
			addCriterion("c_id <", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThanOrEqualTo(Integer value) {
			addCriterion("c_id <=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdIn(List<Integer> values) {
			addCriterion("c_id in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotIn(List<Integer> values) {
			addCriterion("c_id not in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdBetween(Integer value1, Integer value2) {
			addCriterion("c_id between", value1, value2, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotBetween(Integer value1, Integer value2) {
			addCriterion("c_id not between", value1, value2, "cId");
			return (Criteria) this;
		}

		public Criteria andCNameIsNull() {
			addCriterion("c_name is null");
			return (Criteria) this;
		}

		public Criteria andCNameIsNotNull() {
			addCriterion("c_name is not null");
			return (Criteria) this;
		}

		public Criteria andCNameEqualTo(String value) {
			addCriterion("c_name =", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameNotEqualTo(String value) {
			addCriterion("c_name <>", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameGreaterThan(String value) {
			addCriterion("c_name >", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameGreaterThanOrEqualTo(String value) {
			addCriterion("c_name >=", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameLessThan(String value) {
			addCriterion("c_name <", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameLessThanOrEqualTo(String value) {
			addCriterion("c_name <=", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameLike(String value) {
			addCriterion("c_name like", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameNotLike(String value) {
			addCriterion("c_name not like", value, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameIn(List<String> values) {
			addCriterion("c_name in", values, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameNotIn(List<String> values) {
			addCriterion("c_name not in", values, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameBetween(String value1, String value2) {
			addCriterion("c_name between", value1, value2, "cName");
			return (Criteria) this;
		}

		public Criteria andCNameNotBetween(String value1, String value2) {
			addCriterion("c_name not between", value1, value2, "cName");
			return (Criteria) this;
		}

		public Criteria andCDateIsNull() {
			addCriterion("c_date is null");
			return (Criteria) this;
		}

		public Criteria andCDateIsNotNull() {
			addCriterion("c_date is not null");
			return (Criteria) this;
		}

		public Criteria andCDateEqualTo(Date value) {
			addCriterion("c_date =", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateNotEqualTo(Date value) {
			addCriterion("c_date <>", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateGreaterThan(Date value) {
			addCriterion("c_date >", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateGreaterThanOrEqualTo(Date value) {
			addCriterion("c_date >=", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateLessThan(Date value) {
			addCriterion("c_date <", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateLessThanOrEqualTo(Date value) {
			addCriterion("c_date <=", value, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateIn(List<Date> values) {
			addCriterion("c_date in", values, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateNotIn(List<Date> values) {
			addCriterion("c_date not in", values, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateBetween(Date value1, Date value2) {
			addCriterion("c_date between", value1, value2, "cDate");
			return (Criteria) this;
		}

		public Criteria andCDateNotBetween(Date value1, Date value2) {
			addCriterion("c_date not between", value1, value2, "cDate");
			return (Criteria) this;
		}

		public Criteria andCIpIsNull() {
			addCriterion("c_ip is null");
			return (Criteria) this;
		}

		public Criteria andCIpIsNotNull() {
			addCriterion("c_ip is not null");
			return (Criteria) this;
		}

		public Criteria andCIpEqualTo(Integer value) {
			addCriterion("c_ip =", value, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpNotEqualTo(Integer value) {
			addCriterion("c_ip <>", value, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpGreaterThan(Integer value) {
			addCriterion("c_ip >", value, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpGreaterThanOrEqualTo(Integer value) {
			addCriterion("c_ip >=", value, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpLessThan(Integer value) {
			addCriterion("c_ip <", value, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpLessThanOrEqualTo(Integer value) {
			addCriterion("c_ip <=", value, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpIn(List<Integer> values) {
			addCriterion("c_ip in", values, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpNotIn(List<Integer> values) {
			addCriterion("c_ip not in", values, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpBetween(Integer value1, Integer value2) {
			addCriterion("c_ip between", value1, value2, "cIp");
			return (Criteria) this;
		}

		public Criteria andCIpNotBetween(Integer value1, Integer value2) {
			addCriterion("c_ip not between", value1, value2, "cIp");
			return (Criteria) this;
		}

		public Criteria andIsorderIsNull() {
			addCriterion("isOrder is null");
			return (Criteria) this;
		}

		public Criteria andIsorderIsNotNull() {
			addCriterion("isOrder is not null");
			return (Criteria) this;
		}

		public Criteria andIsorderEqualTo(Integer value) {
			addCriterion("isOrder =", value, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderNotEqualTo(Integer value) {
			addCriterion("isOrder <>", value, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderGreaterThan(Integer value) {
			addCriterion("isOrder >", value, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderGreaterThanOrEqualTo(Integer value) {
			addCriterion("isOrder >=", value, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderLessThan(Integer value) {
			addCriterion("isOrder <", value, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderLessThanOrEqualTo(Integer value) {
			addCriterion("isOrder <=", value, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderIn(List<Integer> values) {
			addCriterion("isOrder in", values, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderNotIn(List<Integer> values) {
			addCriterion("isOrder not in", values, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderBetween(Integer value1, Integer value2) {
			addCriterion("isOrder between", value1, value2, "isorder");
			return (Criteria) this;
		}

		public Criteria andIsorderNotBetween(Integer value1, Integer value2) {
			addCriterion("isOrder not between", value1, value2, "isorder");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ptf_website
	 * @mbggenerated  Thu Jan 14 16:42:20 GMT+08:00 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ptf_website
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 14 16:40:31 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}